<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" href="assets/images/mmmm-fav-icon.png" type="image/x-icon">
  <title>M.M.M.M. | <?= $pageTitle ?></title>
  <!-- Latest compiled and minified CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="assets/css/style.css">

  <!-- Latest compiled JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>
  <header class="container-fluid p-3">
    <div class="row">
      <img class='col-sm-6 col-md-4' src="assets/images/mmmm-clean-flat-logo.png" alt="MMMM Logo" />
      <div class="col-sm-6 col-md-8 text-center my-auto">
        <h1>Welcome to the M.M.M.M.</h1>
        <p>Best place for merch!</p>
      </div>
    </div>
  </header>

<?php include_once('assets/includes/nav.inc'); ?>