    <footer>
      &copy;2025 Trevor Student
    </footer>
    <details open>
      <summary>Debug Info</summary>
      <h4>GET</h4>
      <?php
      //preshow($_GET);
      ?>

      <h4>POST</h4>
      <?php
      //preshow($_POST);
      ?>

      <h4>FILES</h4>
      <?php
      //preshow($_FILES);
      ?>

      <h4>SESSION</h4>
      <?php
      //preshow($_SESSION);
      ?>

    </details>
  </div>
</body>

</html>