        <nav class="navbar navbar-expand-sm bg navbar-dark mb-3 rounded">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link " href="index.php">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="books.php">Books</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="new_book.php">New Book</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="gallery.php">Gallery</a>
                </li>
            </ul>
        </nav>